# Generated by Django 6.0.4 on 2026-04-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='ni_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='utr_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
