# Generated by Django 6.0.4 on 2026-04-20 10:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_date_of_birth_driver_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('active', 'Active')], default='invited', max_length=20),
        ),
    ]
